### ISSUE TITLE
Autotools error (see message)

### ISSUE THREAD

**Issue by dany-on-demand** [Serranya/sdl2-vala-lazy-foo#2]
Makefile.am:5: compiling `src/test.c' in subdir requires`AM_PROG_CC_C_O' in `configure.ac'

tried compiling 02_getting_an_image_on_the_screen on raspbian (raspberry pi) like described [here](http://askubuntu.com/questions/27677/cannot-find-install-sh-install-sh-or-shtool-in-ac-aux)

and got that, added that line somewhere in configure.ac and after I used [your vapi](https://github.com/Serranya/sdl2-vapi) it compiled

also, when launching, it threw up:

```
error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

I got SDL2 using https://cutmywire.wordpress.com/2013/11/16/raspberry-pi-sdl2-installation-frustfrei/ and it seemed to work, I can't find anything sdl related in /usr/lib though

anyway too tired for this, I'll take a look at it later

**Comment by Serranya** [comment]
Did you install the precompiled SDL libraries or did you compile them yourself? (I guess you used the precompiled libs)

EDIT: You needed to add AM_PROG_CC_C_O because of your older Autotools version.

**Comment by dany-on-demand** [comment]
I did both actually, I was trying to get [Simple2d](http://www.simple2d.com/), I compiled 2.0.3 using the script but simple2d errored out on that, so I downloaded 2.0.1 using the script. Which got compiling Simple2d further but then it threw up that it's missing GLES2/gl2.h and I couldn't find how to fix that anywhere. All I could find is that raspbian is supposed to come with the libs but then why the hell didn't it werk :|

**Comment by Serranya** [comment]
Raspbian only has SDL 1.2.

My examples actually should work if you compile and install SDL.
The installer for the precompiled SDL libs seems not to copy the requred .pc files.

The installer downloads https://www.dropbox.com/s/sqoi0sy0snbpeb8/sdl2.0.1.zip at line 57 and copies the binaries. Try to manually copy the ".pc" files

```
wget https://www.dropbox.com/s/sqoi0sy0snbpeb8/sdl2.0.1.zip
unzip sdl2.0.1.zip -d sdl
sudo cp sdl/lib/pkgconfig/* /lib/pkgconfig
rm -rf sdl sdl2.0.1.zip
```

then post the output of:

```
pkg-config sdl2 --libs --cflags
```

**Comment by dany-on-demand** [comment]
Thanks, I'll try it.

**Comment by Serranya** [comment]
@Dany0 were you able to resolve the issue ?

**Comment by dany-on-demand** [comment]
@Serranya wasn't able to find time just yet

I'll try to compile it in a vm

EDIT:
OK I had to use your vapis but it compiled. Yay!

**Comment by Serranya** [comment]
great :) I will close the issue.

**Comment by dany-on-demand** [comment]
Just to be clear, I only wanted to compile (cross compile to windows once that's working) on the raspberry so that I didn't have to open up a VM. But I wanted to close the issue anyway since it turned out that the rpi is really only good as a target platform and a VM is just a ton more convenient.

So yeah if you want to run sdl2+vala on an rpi, just cross compile it. Just my 5 cents.

EDIT:
Also, to be clear, it compiled in the VM, not on the rpi.
